### ISSUE TITLE
Password Safe needs multiple minutes to open database opened by KeePass 2  & KeePass XC in a few seconds

### ISSUE THREAD

**Issue by ell1e** [flathub/org.gnome.PasswordSafe#11]
Password Safe needs multiple minutes to open database opened by KeePass 2 & KeePass XC in a few seconds. To me this seems to fundamentally undermine a safe encrypted local password store, because if the crypto is so inefficient that an attacker can just pick a more efficient one and brute force the file open in no time unless the user is basically okay with near unusable app loading times.

**Comment by A6GibKm** [comment]
Please do not use this repository for reporting issues not directly related to the distribution of the app.

Regarding the issue itself, the app is quick¹ to open the database, it takes around 0.5s for a big one. Whats really slow is generating a widget for each entry. This is an issue that will go away once I can migrate the list widget to a GtkListView but there are some bugs in GTK 4 that block that change.

1. We delegate all that to https://github.com/libkeepass/pykeepass, if you think this is still slow please report it there.

**Comment by A6GibKm** [comment]
By the way, the repo for the app is https://gitlab.gnome.org/World/secrets, and the latest version is called https://github.com/flathub/org.gnome.World.Secrets.

**Comment by ell1e** [comment]
Multiple minutes for something that opens in seconds in the others is too slow, yes. I do admit I don't however know for sure if it's the crypto part, so if you have a better guess let me know. I just couldn't think of anything else that would make sense as the culprit, but who knows I guess.

**Comment by A6GibKm** [comment]
As I said previously, the cause is creating hundred of widgets and not the crypto part. And it will be substantially faster once an upstream bug is fixed. 

Might I ask what algorithms are used in your database? Using a relatively big database (1000 entries) I am still able to open it in less than 3 seconds on a slow laptop.

**Comment by ell1e** [comment]
AES/Rijndael (256-bit key, FIPS 197) encryption, with key derivative function AES-KDF with >7 million iterations.

If a larger database takes 3 seconds on a slow laptop for you due to the widget issue, I'm a bit baffled how that would explain it taking multiple minutes though :eyes: I dunno just feels to me like something else may be involved

**Comment by A6GibKm** [comment]
We are not using the same algorithms, it is entirely possible that pykeepass (the upstream library we use) has an issue for that algorithm (or that specific choice of parameters) which causes the extremely slow load time. 

If you attach me an empty (new)  database using the same algorithms I can debug and report upstream if this is the case.
